server:
  port: 8282

spring:
  application:
    name: film-planner-app

  datasource:

    url: jdbc:h2:mem:filmplannerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: -1

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    com.example.filmplanner: DEBUG