server:
  port: 8282

spring:
  application:
    name: film-planner-app

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 16032005
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: -1

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    com.example.filmplanner: DEBUG